# src/auv_slam/config/navigation_params.yaml
# FIXED NAVIGATION FOR SMART SEARCH AND SHORTEST PATH

gate_navigator_node:
  ros__parameters:
    # Depth control
    target_depth: -1.5
    depth_tolerance: 0.3  # Looser tolerance for faster depth acquisition
    depth_correction_gain: 1.5  # Higher gain for faster response
    
    # CRITICAL FIX 1: Smart search pattern
    search_forward_speed: 0.5  # Move forward while searching (not just rotate!)
    search_rotation_speed: 0.15  # Gentle rotation for scanning
    
    # CRITICAL FIX 2: Faster approach for shortest time
    approach_speed: 0.7  # Good balance of speed and control
    
    # CRITICAL FIX 3: Maximum passing speed
    passing_speed: 1.0  # Full speed through gate
    passing_duration: 8.0  # Ensure complete passage
    
    # CRITICAL FIX 4: Continuous alignment (no "stopping to align")
    alignment_threshold: 0.15  # Not used in continuous drift approach
    yaw_correction_gain: 1.2  # High gain for sharp, responsive turns
    
    # Distance thresholds
    approach_distance: 3.0  # Start approaching at 3m
    passing_distance: 1.5  # Start passing mode at 1.5m